/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'background': '#fff8f7',
        'on-secondary': '#ffffff',
        'on-tertiary-container': '#96a1ce',
        'tertiary-container': '#2c375e',
        'on-primary-fixed-variant': '#871f1c',
        'on-secondary-container': '#416e4d',
        'on-tertiary-fixed': '#0d193f',
        'tertiary': '#162147',
        'secondary': '#3b6848',
        'on-tertiary': '#ffffff',
        'outline-variant': '#dfbfbc',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'surface-container': '#ffe9e8',
        'primary-fixed': '#ffdad6',
        'surface-container-low': '#fff0f0',
        'inverse-on-surface': '#ffedec',
        'surface-dim': '#ead5d5',
        'surface': '#fff8f7',
        'secondary-fixed': '#bdefc6',
        'surface-tint': '#a83730',
        'tertiary-fixed-dim': '#bac5f4',
        'primary-container': '#741010',
        'on-surface-variant': '#57413f',
        'on-secondary-fixed-variant': '#234f32',
        'on-primary-container': '#ff7b6f',
        'outline': '#8b716e',
        'on-secondary-fixed': '#00210d',
        'inverse-surface': '#3a2d2d',
        'primary': '#510003',
        'inverse-primary': '#ffb4ab',
        'error': '#ba1a1a',
        'surface-bright': '#fff8f7',
        'on-surface': '#241919',
        'on-background': '#241919',
        'secondary-container': '#bdefc6',
        'on-tertiary-fixed-variant': '#3a456d',
        'surface-container-highest': '#f3dedd',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed': '#410002',
        'on-error-container': '#93000a',
        'surface-container-high': '#f9e3e3',
        'on-primary': '#ffffff',
        'secondary-fixed-dim': '#a1d2ab',
        'surface-variant': '#f3dedd',
        'primary-fixed-dim': '#ffb4ab',
        'tertiary-fixed': '#dce1ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '16px',
        'container-padding-mobile': '24px',
        'container-padding-desktop': '48px',
        unit: '8px',
        'element-gap': '12px',
      },
      fontFamily: {
        'label-md': ['Hanken Grotesk', 'sans-serif'],
        caption: ['Hanken Grotesk', 'sans-serif'],
        'display-lg': ['Libre Caslon Text', 'serif'],
        'headline-sm': ['Libre Caslon Text', 'serif'],
        'display-lg-mobile': ['Libre Caslon Text', 'serif'],
        'headline-md': ['Libre Caslon Text', 'serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'display-lg-mobile': ['32px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
